FROM ruby:2.5
RUN apt-get update && apt-get install -y \
      build-essential \
      libpq-dev \
      nodejs \
      postgresql-client \
      yarn
WORKDIR /product-register
COPY Gemfile Gemfile.lock /product-register/
RUN bundle install

COPY . . 
#カレントディレクトリのファイルを全てコピーする。本番環境用では、必要なファイルは全てコンテナに入れて、その上でサーバーにデプロイするのが一般的
CMD [ "rails", "s" ]
#サーバー上でRailsのアプリサーバを起動させる。これをしないと、Railsアプリが動かないままなので必ず付与する！！！
